server:
  servlet:
    context-path: /CampusCats
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///campus_cats_management1?useSSL=false&useServerPrepStmts=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl